/// <reference types="node" />
// build-tokens-src/config.mjs
// Reads the --config flag from argv, imports the project config file,
// resolves all paths and exports them for build-tokens.mjs.
//
// Keeping this logic separate from the entry point makes it easier to test
// and reuse in other scripts.

/* globals process */

import * as path from 'node:path';
import { pathToFileURL } from 'node:url';
import { resolveSourcePaths } from './resolve-source-paths.mjs';

// ---------------------------------------------------------------------------
// Read the --config flag
// ---------------------------------------------------------------------------
const args = process.argv.slice(2);
const configFlagIndex = args.indexOf('--config');

if (configFlagIndex === -1 || !args[configFlagIndex + 1]) {
  // eslint-disable-next-line no-console
  console.error(
    'Error: you must specify the config file with --config ./path/to/config/file'
  );
  process.exit(1);
}

const configArgPath = args[configFlagIndex + 1];
export const configAbsPath = path.resolve(process.cwd(), configArgPath);
export const configDir     = path.dirname(configAbsPath);

// ---------------------------------------------------------------------------
// Import the project config
// ---------------------------------------------------------------------------
const buildConfig = (await import(pathToFileURL(configAbsPath).href)).default;

// Helper: resolves a path relative to the config directory.
// Leaves already-absolute paths untouched.
/** @param {string} p */
const resolveFromConfig = (p) => path.resolve(configDir, p);

// ---------------------------------------------------------------------------
// Path resolution
// ---------------------------------------------------------------------------

// CSS output
export const buildPath = resolveFromConfig(buildConfig.buildPath);
export const destFile  = buildConfig.destFile;

// Stylelint
export const stylelintConfigPath = resolveFromConfig(buildConfig.stylelintConfigPath);

// Penpot — platform is active only if penpotBuildPath is set in the config
const penpotBuildPathRaw = buildConfig.penpotBuildPath ?? null;
export const penpotBuildPath = penpotBuildPathRaw ? resolveFromConfig(penpotBuildPathRaw) : null;

// penpotDestFile: base name (no extension) for the aggregated output file.
// null  → one file per source (mirrors the source structure)
// string → single aggregated file (e.g. 'tokens' → 'tokens.jsonc')
// The extension is added automatically based on penpotFormat.
export const penpotDestFile = buildConfig.penpotDestFile ?? null;

// penpotFormat: controls output format for Penpot token files.
// 'jsonc' → .jsonc extension + generated-file disclaimer header
// 'json'  → plain .json, no disclaimer
// Any value other than 'jsonc' is normalised to 'json'.
export const penpotFormat = buildConfig.penpotFormat === 'jsonc' ? 'jsonc' : 'json';

// penpotExpressions: controls how math expressions in dimension token values are handled.
//   'keep'    (default) — write the expression as-is
//   'calc'    — wrap in CSS calc()
//   'resolve' — evaluate numerically; unit inherited from the first referenced token
const VALID_EXPR_MODES = ['keep', 'calc', 'resolve'];
export const penpotExpressions = VALID_EXPR_MODES.includes(buildConfig.penpotExpressions)
  ? buildConfig.penpotExpressions
  : 'resolve';

// mergeCustomProps: if true, custom properties already present in the CSS
// destination file take priority over the ones generated by this build (see
// build-tokens-src/merge-css.mjs). Default: false.
export const mergeCustomProps = buildConfig.mergeCustomProps === true;

// colorPropertiesPrefixes: custom properties whose first hyphen-separated
// name segment matches one of these prefixes are grouped together and moved
// to the beginning of the generated CSS file (see formats/css.mjs). Default: [].
export const colorPropertiesPrefixes = Array.isArray(buildConfig.colorPropertiesPrefixes)
  ? buildConfig.colorPropertiesPrefixes
  : [];

// ---------------------------------------------------------------------------
// Source: resolve patterns relative to the config directory and normalise to
// forward-slash absolute paths (fast-glob, used internally by Style Dictionary,
// requires forward slashes even on Windows). See resolve-source-paths.mjs.
//
// WARNING: in the project config file, avoid building glob patterns with
// path.join() — it may corrupt the pattern syntax. Use template literals:
//   OK:  `${minimo_path}/**/*.{json,mjs}`
//   NO:  path.join(minimo_path, '/**/*.{json,mjs}')
// ---------------------------------------------------------------------------
export const source = resolveSourcePaths(buildConfig.source, configDir);
