// build-tokens-src/merge-css.mjs
// Supports the `mergeCustomProps` config option: pre-existing custom
// properties in the CSS destination file take priority over the ones
// generated by the current build (manual overrides/additions survive rebuilds).
//
// Usage:
//   1. Call loadExistingCustomProps(absDestPath) BEFORE Style Dictionary runs,
//      since it reads the file that is about to be overwritten.
//   2. The css/variables-sorted format (see formats/css.mjs) calls
//      mergeCustomProps(generatedMap) while building the output, right before
//      serialising the final CSS text.

import { existsSync, readFileSync } from 'node:fs';

const CUSTOM_PROP_RE = /^\s*--([\w-]+):\s*(.+)$/gm;

/**
 * Parses `--name: <tail>` declarations out of a CSS text block. <tail> is
 * captured verbatim (value, terminating `;`, and anything else on the same
 * line, e.g. a trailing comment) so it round-trips unchanged through a merge.
 * Only single-line declarations are supported.
 * @param {string} cssText
 * @returns {Record<string,string>} name → declaration-tail map, in first-seen order
 */
export const parseCustomProps = (cssText) => {
  /** @type {Record<string,string>} */
  const map = {};
  for (const match of cssText.matchAll(CUSTOM_PROP_RE)) {
    map[match[1]] = match[2].trim();
  }
  return map;
};

// null = merge disabled, or destination file not found yet (first build)
/** @type {Record<string,string>|null} */
let existingCustomProps = null;

/**
 * Reads the CSS destination file (if it exists) and stores a name → value
 * map of its current custom properties for later merging.
 * @param {string} absDestPath absolute path of the CSS file to read
 * @returns {Record<string,string>|null}
 */
export const loadExistingCustomProps = (absDestPath) => {
  existingCustomProps = existsSync(absDestPath)
    ? parseCustomProps(readFileSync(absDestPath, 'utf8'))
    : null;
  return existingCustomProps;
};

/**
 * Merges freshly generated custom properties with the ones previously loaded
 * via loadExistingCustomProps(). Pre-existing values take priority; custom
 * properties found only in the pre-existing file (no longer generated) are
 * kept as well.
 * @param {Record<string,string>} generated name → value map produced by this build
 * @returns {Record<string,string>}
 */
export const mergeCustomProps = (generated) =>
  existingCustomProps ? { ...generated, ...existingCustomProps } : generated;
