/*! minimo - json-table: main structure builder */

import * as styles from '../json-table-component.module.css';
import { domBuilder } from '../../../utilities/dom-builder/dom-builder.js';
import { classnames } from '../../../utilities/classnames.js';
import { infoSection } from './info-section.js';

/** @typedef {import('./defaults.js').JsonTableParams} JsonTableParams */

/**
 * Elements generated by the component, collected during the build.
 * @typedef {Object} JsonTableElements
 * @property {HTMLElement} [wrapper] - Main wrapper (`section`), contains info section and table
 * @property {HTMLElement} [infoOuter] - Outer info container
 * @property {HTMLElement} [info] - Info container (flex row: info text + search)
 * @property {HTMLElement} [resultInfo] - Info text container
 * @property {HTMLInputElement} [searchInput] - Search input (only when `search` is true)
 * @property {HTMLElement} [tableWrapper] - Div wrapping the table (`table-responsive` by default)
 * @property {HTMLTableElement} [table] - The `<table>` element
 */

/**
 * Builds the whole component structure inside `host` (emptied first) via domBuilder.
 *
 * Generated structure:
 * ```
 * section.wrapper[mainWrapperExtraClass]
 *   div.infoOuter[outerInfoExtraClass]
 *     div.info[infoExtraClass]
 *       div.resultInfo
 *       div.search > input[type=search]     (if `search`)
 *   div[tableWrapperClass]
 *     table#tableId[tableClass]
 *       caption                             (if `caption`)
 * ```
 *
 * TODO thead / tbody / tfoot: step successivo (parametro `cols` e rendering delle righe)
 *
 * @param {HTMLElement} host - The `<json-table>` element
 * @param {JsonTableParams} params - Resolved params
 * @returns {JsonTableElements} References to the generated elements
 *
 * @example
 * const elements = mainBuilder(el, {
 *   ...defaults,
 *   caption: 'Utenti',                  // default: null
 *   search: true,                       // default: true
 *   tableId: 'users-table',             // default: null
 *   tableWrapperClass: 'table-responsive', // default: 'table-responsive'
 *   tableClass: 'table table-bordered', // default: 'table table-bordered'
 *   mainWrapperExtraClass: null,        // default: null
 *   outerInfoExtraClass: null,          // default: null
 *   infoExtraClass: null                // default: null
 * });
 * elements.table; // → HTMLTableElement
 */
export function mainBuilder(host, params) {

  /** @type {JsonTableElements} */
  const elements = {};

  domBuilder([
    {
      tag: 'section',
      className: classnames(styles.wrapper, params.mainWrapperExtraClass),
      callback: el => { elements.wrapper = /** @type {HTMLElement} */ (el); },
      children: [

        ...infoSection(params, elements),

        {
          className: classnames(params.tableWrapperClass),
          callback: el => { elements.tableWrapper = /** @type {HTMLElement} */ (el); },
          children: [
            {
              tag: 'table',
              id: params.tableId,
              className: classnames(styles.table, params.tableClass),
              callback: el => { elements.table = /** @type {HTMLTableElement} */ (el); },
              children: [
                {
                  tag: 'caption',
                  condition: params.caption != null,
                  content: params.caption
                }
              ]
            }
          ]
        }
      ]
    }
  ], host, { emptyParent: true });

  return elements;
}
