/*! minimo - json-table: main structure builder */

import * as styles from '../json-table-component.module.css';
import { domBuilder } from '../../../utilities/dom-builder/dom-builder.js';
import { classnames } from '../../../utilities/classnames.js';
import { defaults } from './defaults.js';
import { infoSectionPart, resultInfoPart, searchPart } from './info-section.js';
import { tablePart } from './table-builder.js';

/** @typedef {import('../json-table-component.js').JsonTable} JsonTable */
/** @typedef {import('./defaults.js').TemplateItem} TemplateItem */

/**
 * Elements generated by the component, collected during the build.
 * @typedef {Object} JsonTableElements
 * @property {HTMLElement} [wrapper] - Main wrapper (`section`), contains the template parts
 * @property {HTMLElement} [infoOuter] - Outer info container
 * @property {HTMLElement} [info] - Info container (flex row: info text + search)
 * @property {HTMLElement} [resultInfo] - Info text container
 * @property {HTMLInputElement} [searchInput] - Search input (only when `search` is true)
 * @property {HTMLElement} [tableWrapper] - Div wrapping the table (`table-responsive` by default)
 * @property {HTMLTableElement} [table] - The `<table>` element
 * @property {HTMLTableSectionElement} [thead] - The `<thead>` element
 * @property {HTMLTableSectionElement} [tbody] - The `<tbody>` element
 * @property {HTMLTableSectionElement} [tfoot] - The `<tfoot>` element (only when `tfoot` is true)
 */

/**
 * Replaces, recursively (`children` and array `content`), every `{ slot: 'name' }` item of a
 * template with the corresponding built-in part. Unknown slots are reported in the console
 * and skipped. Non-slot items are shallow-copied, so the original template is never mutated.
 *
 * @param {Array<TemplateItem|string|Node>} items - Template items
 * @param {Object<string, DomBuilderItem>} parts - Built-in parts, keyed by slot name
 * @returns {Array<DomBuilderItem|string|Node>}
 *
 * @example
 * expandSlots([{ className: 'row', children: [{ slot: 'search' }, { slot: 'resultInfo' }] }, { slot: 'table' }], parts);
 * // → [{ className: 'row', children: [<search part>, <resultInfo part>] }, <table part>]
 */
export function expandSlots(items, parts) {

  /** @type {Array<DomBuilderItem|string|Node>} */
  const result = [];

  items.forEach(item => {

    if (item == null || typeof item !== 'object' || item instanceof Node) {
      result.push(item);
      return;
    }

    if (item.slot != null) {
      const part = parts[item.slot];
      if (!part) {
        // eslint-disable-next-line no-console
        console.error(`[json-table] template: slot \`${item.slot}\` non riconosciuto (disponibili: ${Object.keys(parts).join(', ')})`);
        return;
      }
      result.push(part);
      return;
    }

    /** @type {DomBuilderItem} */
    const copy = { ...item };

    if (Array.isArray(copy.children)) {
      copy.children = expandSlots(copy.children, parts);
    }
    if (Array.isArray(copy.content)) {
      copy.content = /** @type {DomBuilderItem[]} */ (expandSlots(copy.content, parts));
    }

    result.push(copy);
  });

  return result;
}


/**
 * Builds the whole component structure inside the host element (emptied first) via domBuilder:
 * a fixed main wrapper whose content is defined by `params.template`.
 *
 * Available template slots (see `TemplateItem`):
 * - `infoSection` → `infoSectionPart()` (info text + search input)
 * - `resultInfo`  → `resultInfoPart()` (info text only)
 * - `search`      → `searchPart()` (search input only)
 * - `table`       → `tablePart()` (table wrapper + table with caption, thead, tbody, tfoot)
 *
 * Generated structure with the default template (`[{ slot: 'infoSection' }, { slot: 'table' }]`):
 * ```
 * section.wrapper[classes.wrapper]
 *   div.infoOuter[classes.infoOuter]
 *     div.info[classes.info]
 *       div.resultInfo
 *       div.search > input[type=search]     (if `search`)
 *   div.tableWrapper[classes.tableWrapper]
 *     table#tableId.table[classes.table]
 *       caption                             (if `caption`)
 *       thead / tbody / tfoot               (tfoot if `tfoot`)
 * ```
 *
 * The `<tbody>` and `<tfoot>` are created empty: see `renderTbody()` / `renderTfoot()`.
 *
 * @param {JsonTable} jt - The component instance (host element, `params`, `cols`)
 * @returns {JsonTableElements} References to the generated elements
 *
 * @example
 * jt.params.template = [
 *   { className: 'flex gap-2', children: [{ slot: 'search' }, { slot: 'resultInfo' }] },
 *   { slot: 'table' }
 * ];
 * const elements = mainBuilder(jt);
 * elements.table; // → HTMLTableElement
 */
export function mainBuilder(jt) {

  const { params } = jt;

  /** @type {JsonTableElements} */
  const elements = {};

  /** @type {Object<string, DomBuilderItem>} */
  const parts = {
    infoSection: infoSectionPart(params, elements),
    resultInfo: resultInfoPart(params, elements),
    search: searchPart(params, elements),
    table: tablePart(jt, elements)
  };

  const template = typeof params.template === 'function'
    ? params.template(parts, params)
    : params.template;

  const children = expandSlots(
    Array.isArray(template) ? template : /** @type {TemplateItem[]} */ (defaults.template),
    parts
  );

  domBuilder([
    {
      tag: 'section',
      className: classnames(styles.wrapper, params.classes.wrapper),
      callback: el => { elements.wrapper = /** @type {HTMLElement} */ (el); },
      children
    }
  ], jt, { emptyParent: true });

  return elements;
}
