/*! minimo - json-table: main structure builder */

import * as styles from '../json-table-component.module.css';
import { domBuilder } from '../../../utilities/dom-builder/dom-builder.js';
import { classnames } from '../../../utilities/classnames.js';
import { defaults } from './defaults.js';
import { infoSectionPart, resultInfoPart, searchPart } from './info-section.js';
import { tablePart, tableFooterPart, captionPart, captionId } from './table-builder.js';
import { paginationPart } from './pagination.js';

/** @typedef {import('../json-table-component.js').JsonTable} JsonTable */
/** @typedef {import('./defaults.js').TemplateItem} TemplateItem */
/** @typedef {import('./defaults.js').TemplateSlot} TemplateSlot */

/**
 * Elements generated by the component, collected during the build.
 * @typedef {Object} JsonTableElements
 * @property {HTMLElement} [wrapper] - Main wrapper (`section`), contains the template parts
 * @property {HTMLElement} [infoOuter] - Outer info container
 * @property {HTMLElement} [info] - Info container (flex row: info text + search)
 * @property {HTMLElement} [resultInfo] - Info text container
 * @property {HTMLInputElement} [searchInput] - Search input (only when `search` is true)
 * @property {HTMLElement} [tableWrapper] - Div wrapping the table (`table-responsive` by default)
 * @property {HTMLTableElement} [table] - The `<table>` element
 * @property {HTMLTableSectionElement} [thead] - The `<thead>` element
 * @property {HTMLTableSectionElement} [tbody] - The `<tbody>` element
 * @property {HTMLTableSectionElement} [tfoot] - The `<tfoot>` element (only when `tfoot` is true)
 * @property {HTMLElement} [tableFooter] - Footer bar below the table (caption + pagination), when rendered
 * @property {HTMLElement} [caption] - Caption container (only when `caption` is set)
 * @property {HTMLElement} [pagination] - Pagination `<nav>` (only when `perPage` > 0)
 */

/**
 * Whether a template item is a slot placeholder.
 * @param {*} item
 * @returns {item is { slot: TemplateSlot }}
 */
function isSlot(item) {
  return item != null && typeof item === 'object' && !(item instanceof Node) && typeof item.slot === 'string';
}


/**
 * Collects, recursively (`children` and array `content`), the names of the slots used by a template.
 *
 * @param {Array<TemplateItem|string|Node>} items - Template items
 * @param {Set<string>} [found=new Set()] - Accumulator (default: new Set())
 * @returns {Set<string>}
 *
 * @example
 * collectSlots([{ slot: 'table' }, { children: [{ slot: 'pagination' }] }]); // → Set { 'table', 'pagination' }
 */
export function collectSlots(items, found = new Set()) {

  items.forEach(item => {
    if (isSlot(item)) {
      found.add(item.slot);
    } else if (item != null && typeof item === 'object' && !(item instanceof Node)) {
      if (Array.isArray(item.children)) {
        collectSlots(item.children, found);
      }
      if (Array.isArray(item.content)) {
        collectSlots(/** @type {TemplateItem[]} */ (item.content), found);
      }
    }
  });

  return found;
}


/**
 * Replaces, recursively (`children` and array `content`), every `{ slot: 'name' }` item of a
 * template with the corresponding built-in part. Unknown slots are reported in the console
 * and skipped. Non-slot items are shallow-copied, so the original template is never mutated.
 *
 * @param {Array<TemplateItem|string|Node>} items - Template items
 * @param {Object<string, DomBuilderItem>} parts - Built-in parts, keyed by slot name
 * @returns {Array<DomBuilderItem|string|Node>}
 *
 * @example
 * expandSlots([{ className: 'row', children: [{ slot: 'search' }, { slot: 'resultInfo' }] }, { slot: 'table' }], parts);
 * // → [{ className: 'row', children: [<search part>, <resultInfo part>] }, <table part>]
 */
export function expandSlots(items, parts) {

  /** @type {Array<DomBuilderItem|string|Node>} */
  const result = [];

  items.forEach(item => {

    if (item == null || typeof item !== 'object' || item instanceof Node) {
      result.push(/** @type {string|Node} */ (item));
      return;
    }

    if (isSlot(item)) {
      const part = parts[item.slot];
      if (!part) {
        // eslint-disable-next-line no-console
        console.error(`[json-table] template: slot \`${item.slot}\` non riconosciuto (disponibili: ${Object.keys(parts).join(', ')})`);
        return;
      }
      result.push(part);
      return;
    }

    /** @type {DomBuilderItem} */
    const copy = /** @type {DomBuilderItem} */ ({ ...item });

    if (Array.isArray(item.children)) {
      copy.children = expandSlots(item.children, parts);
    }
    if (Array.isArray(item.content)) {
      copy.content = /** @type {DomBuilderItem[]} */ (expandSlots(/** @type {TemplateItem[]} */ (item.content), parts));
    }

    result.push(copy);
  });

  return result;
}


/**
 * Builds the whole component structure inside the host element (emptied first) via domBuilder:
 * a fixed main wrapper whose content is defined by `params.template`.
 *
 * Available template slots (see `TemplateItem`):
 * - `infoSection` → `infoSectionPart()` (info text + search input)
 * - `resultInfo`  → `resultInfoPart()` (info text only)
 * - `search`      → `searchPart()` (search input only)
 * - `table`       → `tablePart()` (table wrapper + table with thead, tbody, tfoot, plus the footer bar)
 * - `caption`     → `captionPart()` (caption container; part of the `table` footer bar unless placed explicitly)
 * - `pagination`  → `paginationPart()` (pagination nav; idem)
 *
 * Generated structure with the default template (`[{ slot: 'infoSection' }, { slot: 'table' }]`):
 * ```
 * section.wrapper[classes.wrapper]
 *   div.infoOuter[classes.infoOuter]
 *     div.info[classes.info]
 *       div.resultInfo
 *       div.search > input[type=search]     (if `search`)
 *   div.tableOuter
 *     div.tableWrapper[classes.tableWrapper]
 *       table#tableId.table[classes.table]
 *         thead / tbody / tfoot             (tfoot if `tfoot`)
 *     div.tableFooter[classes.tableFooter]  (if `caption` or `perPage` > 0)
 *       div.caption                         (if `caption`)
 *       nav.pagination                      (if `perPage` > 0)
 * ```
 *
 * The `<tbody>`, `<tfoot>` and pagination are created empty: see `renderTbody()`, `renderTfoot()`
 * and `renderPagination()`.
 *
 * @param {JsonTable} jt - The component instance (host element, `params`, `cols`)
 * @returns {JsonTableElements} References to the generated elements
 *
 * @example
 * jt.params.template = [
 *   { className: 'flex gap-2', children: [{ slot: 'search' }, { slot: 'pagination' }] },
 *   { slot: 'table' },   // footer bar with the caption only: the pagination is placed above
 *   { slot: 'resultInfo' }
 * ];
 * const elements = mainBuilder(jt);
 * elements.table; // → HTMLTableElement
 */
export function mainBuilder(jt) {

  const { params } = jt;

  /** @type {JsonTableElements} */
  const elements = {};

  const capId = captionId(params);
  const captionItem = captionPart(jt, elements, capId);
  const paginationItem = paginationPart(jt, elements);

  // footer bar parts: removed below when the template places them elsewhere
  /** @type {DomBuilderItem[]} */
  const footerChildren = [captionItem, paginationItem];
  const footerBar = tableFooterPart(jt, elements, footerChildren);

  /** @type {Object<string, DomBuilderItem>} */
  const parts = {
    infoSection: infoSectionPart(params, elements),
    resultInfo: resultInfoPart(params, elements),
    search: searchPart(params, elements),
    caption: captionItem,
    pagination: paginationItem,
    table: tablePart(jt, elements, footerBar, capId)
  };

  const template = typeof params.template === 'function'
    ? params.template(parts, params)
    : params.template;

  const items = Array.isArray(template) ? template : /** @type {TemplateItem[]} */ (defaults.template);
  const usedSlots = collectSlots(items);

  ['caption', 'pagination'].forEach(slot => {
    if (usedSlots.has(slot)) {
      footerChildren.splice(footerChildren.indexOf(parts[slot]), 1);
    }
  });
  footerBar.condition = footerChildren.some(item => item.condition !== false);

  domBuilder([
    {
      tag: 'section',
      className: classnames(styles.wrapper, params.classes.wrapper),
      callback: el => { elements.wrapper = /** @type {HTMLElement} */ (el); },
      children: expandSlots(items, parts)
    }
  ], jt, { emptyParent: true });

  return elements;
}
