/*! minimo - json-table: thead */

import * as styles from '../json-table-component.module.css';
import { classnames } from '../../../utilities/classnames.js';
import { setContent } from './content-utils.js';
import { iconContent } from './icons.js';

/** @typedef {import('./defaults.js').JsonTableParams} JsonTableParams */
/** @typedef {import('../json-table-component.js').JsonTable} JsonTable */
/** @typedef {import('./main-builder.js').JsonTableElements} JsonTableElements */

/** @typedef {'none'|'ascending'|'descending'} SortState */

/**
 * Updates the sort state of a sortable `<th>`: `aria-sort` attribute (removed when `none`),
 * icon and `title`/`aria-label` of the sort button (both describing the action of the next
 * click, e.g. "sort descending" when the ascending sort is active).
 *
 * TODO utilizzata dallo step 3 (ordinamento) ad ogni cambio di stato
 *
 * @param {HTMLTableCellElement} th - The `<th>` generated by `theadPart()`
 * @param {SortState} state - Sort state to apply
 * @param {JsonTableParams} params - Resolved params (icons and labels)
 * @returns {void}
 *
 * @example
 * setSortState(th, 'ascending', params);
 * // th[aria-sort=ascending], icon → params.sortAscArrowIcon, button title → params.labels.sortDesc
 */
export function setSortState(th, state, params) {

  const btn = th.querySelector('button');
  const icon = th.querySelector('[data-jt-sort-icon]');

  if (state === 'none') {
    th.removeAttribute('aria-sort');
  } else {
    th.setAttribute('aria-sort', state);
  }

  const nextLabel = state === 'none'
    ? params.labels.sortAsc
    : (state === 'ascending' ? params.labels.sortDesc : params.labels.sortNone);

  if (btn) {
    const titleText = (th.querySelector('[data-jt-sort-title]')?.textContent ?? '').trim();
    btn.title = nextLabel ?? '';
    btn.setAttribute('aria-label', titleText ? `${titleText}: ${nextLabel}` : (nextLabel ?? ''));
  }

  if (icon) {
    const iconDef = state === 'none'
      ? params.sortNoneArrowIcon
      : (state === 'ascending' ? params.sortAscArrowIcon : params.sortDescArrowIcon);
    setContent(/** @type {HTMLElement} */ (icon), iconContent(iconDef));
  }
}


/**
 * domBuilder item of the `<thead>`.
 *
 * Generated structure:
 * ```
 * thead > tr
 *   th[scope=col][data-key][headerClass]                                   ← not sortable: content = col.title
 *   th.sortable[scope=col][data-key][data-sortable=true][headerClass]      ← sortable
 *     button.sortBtn[classes.sortBtn][type=button][data-key][title][aria-label]
 *       span.sortTitle[data-jt-sort-title]  ← col.title
 *       span.sortIcon[data-jt-sort-icon]    ← sort icon (see `setSortState`)
 * ```
 *
 * The `<thead>` is stored in `elements.thead`.
 * TODO listener sui pulsanti di ordinamento: step 3
 *
 * @param {JsonTable} jt - The component instance (`params`, `cols`)
 * @param {JsonTableElements} elements - Object collecting the generated elements (mutated)
 * @returns {DomBuilderItem}
 *
 * @example
 * domBuilder([{ tag: 'table', children: [theadPart(jt, elements)] }], host);
 * elements.thead; // → HTMLTableSectionElement
 */
export function theadPart(jt, elements) {

  const { params, cols } = jt;

  return {
    tag: 'thead',
    callback: el => { elements.thead = /** @type {HTMLTableSectionElement} */ (el); },
    children: [
      {
        tag: 'tr',
        children: cols.map(col => ({
          tag: 'th',
          className: classnames(col.headerClass, col.sortable && styles.sortable),
          attrs: {
            scope: 'col',
            'data-key': col.key,
            'data-sortable': col.sortable ? 'true' : null
          },
          content: col.sortable ? null : col.title,
          children: col.sortable
            ? [
              {
                tag: 'button',
                className: classnames(styles.sortBtn, params.classes.sortBtn),
                attrs: { type: 'button', 'data-key': col.key },
                children: [
                  { tag: 'span', className: styles.sortTitle, attrs: { 'data-jt-sort-title': '' }, content: col.title },
                  { tag: 'span', className: styles.sortIcon, attrs: { 'data-jt-sort-icon': '', 'aria-hidden': 'true' } }
                ]
              }
            ]
            : [],
          callback: el => {
            if (col.sortable) {
              setSortState(/** @type {HTMLTableCellElement} */ (el), 'none', params);
            }
          }
        }))
      }
    ]
  };
}
