// NB: `.js` negli import
export { controllo_partita_iva } from './src/controllo-partita-iva-IT.js';
export { controllo_codice_fiscale } from './src/controllo-codice-fiscale-IT.js';
export { default as date_in_sequenza } from './src/date-in-sequenza.js';
export { isValidDate, minutesToHour, dateFromISO, dateStringToISO, dateToLocalISOString, formatDate, formatTime, formatDateTime } from './src/date-utilities.js';
export { obfuscate_email, email_antispam } from './src/email-antispam.js';
export { escapeHTML, unescapeHTML } from './src/escapeHTML.js';
export { default as festivita } from './src/festivita.js';
export { bsValidation, disableBtnsOnSubmit, throwErr, setFormElementValue, getFormElementValue } from './src/form-utilities.js';
export { default as genera_pwd } from './src/genera-pwd.js';
export { inputDateRawFallback } from './src/input-date-raw-fallback.js';
export { inputDateSupport, inputDatetimeSupport, inputTimeSupport } from './src/input-date-support.js';
export { jquery_loader } from './src/jquery-ondemand-loader.js';
export { mesi, mesi_0, giorni, giorni_0 } from './src/mesi-giorni-it.js';
export { overlay, remove_overlay } from './src/overlay.js';
export { print_icon } from './src/print-icon.js';
export { $, $$ } from './src/selector-utilities.js';
export { disposeSliding, slideUp, slideDown, slideToggle } from './src/slide-up-down-toggle.js';
export { better_text, title_case, sentence_case, text_cleaner, nl2br } from './src/text-utilities.js';
export { textarea_autosize } from './src/textarea-autosize.js';
export { default as toggle_disabled } from './src/toggle-disabled.js';
export { default as toggle_required } from './src/toggle-required.js';
export { truncate_string } from './src/truncate-string.js';
export { default as unique_id } from './src/unique-id.js';
export { default as url_concat } from './src/url-concat.js';
export { webpSupport } from './src/webp-support.js';
export { dateToMysql } from './src/date-to-mysql.js';
export { getHiddenHeight } from './src/getHiddenHeight.js';
export { enable_submit_btns as enableSubmitBtns } from './src/enable-submit-btns.js';
export { formMultiselect } from './src/form-multiselect.js';
export { getCookie, setCookie } from './src/cookies.js';
export { default as relativeNextDate} from './src/date-relative.js';
export { datesFromTo } from './src/dates-from-to.js';
export { arrayToCsv } from './src/array-to-csv.js';
export { classnames } from './src/classnames.js';
export { parseText } from './src/parse-text.js';
export { stripTags, createId } from './src/create-id.js';
