// All paths are relative to this config file (not to the CWD).

const config = {

  // Path to the stylelint config used to lint the generated CSS file
  stylelintConfigPath: '../stylelint.config.mjs',

  // Output directory for the CSS file generated by Style Dictionary
  buildPath: '../src',

  // Output filename for the generated CSS file
  destFile: 'custom-properties.css',

  // Source token files — accept paths, globs, or a mix of both.
  // Supported formats: .json, .jsonc, .mjs (must export a DTCG-compliant default object)
  //
  // WARNING: do not use path.join() to build glob patterns — it may corrupt
  // the pattern syntax. Use template literals instead:
  //   OK:  `${minimo_path}/**/*.{json,mjs}`
  //   NO:  path.join(minimo_path, '/**/*.{json,mjs}')
  source: [
    './_src/**/*.tokens.mjs',
    '../src/**/*.tokens.mjs',

    // to use in your project, delete the previous entries and uncomment the following ones
    // 'path/to/node_modules/@massimo-cassandro/minimo/design-tokens/_src/**/*.tokens.mjs',
    // 'path/to/node_modules/@massimo-cassandro/minimo/src/**/*.tokens.mjs',
    // 'path/to/your/project/tokens/*.{jsonc,json,mjs}'
  ],

  // If true (default), dimension token values expressed in px are converted
  // to rem in the generated CSS. Values in other units (em, %, vh, dvw, ...)
  // are never touched regardless of this option.
  pxToRem: true,

  // If true, custom properties already present in `destFile` (if exists)
  // take priority over the ones generated by the current build.
  // Properties found only in the pre-existing file (no longer
  // generated) are kept too. Useful to preserve manual overrides/additions
  // made directly in the compiled CSS across rebuilds. Ignored on the first
  // build, when destFile does not exist yet. Default: false.
  // Comments at the end of custom properties are preserved, while full-line ones will be lost.
  mergeCustomProps: false,


  // Named groups of custom properties. Properties whose first hyphen-separated
  // name segment matches one of a group's `prefixes` are pulled out, labelled
  // with the group's `name` and placed at the beginning of the output CSS
  // file, in the order the groups are listed here.
  customPropsGroups: [
    {
      name: 'COLORS',
      prefixes: ['accent', 'primary', 'secondary', 'neutral'],
    },
    {
      name: 'LAYOUT',
      prefixes: ['body', 'layout'],
    },
  ],


  // ---------------------------------------------------------------------------
  // PENPOT / FIGMA
  // ---------------------------------------------------------------------------
  // Optional design tokens output
  // Generates one or more json(c) files in addition to the CSS output file, for use
  // in Penpot or Figma projects or as an alternative to the .mjs source files
  // ---------------------------------------------------------------------------

  // How to handle math expressions in dimension token $values (e.g. "{size.base} * .25"):
  //   'keep'    write the expression unchanged
  //   'calc'    — wrap in CSS calc(): "calc({size.base} * .25)"
  //   'resolve' — (default) evaluate numerically, inheriting the unit from the first referenced token
  //               e.g. {size.base} = 16px, "{size.base} * .25" -> "4px"
  penpotExpressions: 'resolve',

  // Output format for Penpot token files: 'jsonc' or 'json'
  //   'jsonc' -> adds a generated-file disclaimer header, uses .jsonc extension
  //   'json'  -> plain JSON, no disclaimer
  penpotFormat: 'jsonc',

  // Output directory for the Penpot design token files.
  // Set to null (or omit) to disable json output entirely.
  penpotBuildPath: './tokens',

  // Base name (without extension) for the aggregated Penpot output file.
  // The extension is added automatically based on penpotFormat.
  // Set to null (or omit) to generate one file per .mjs source file instead.
  penpotDestFile: null,


  // ---------------------------------------------------------------------------
  // CHECK-UNRESOLVED-CUSTOM-PROPS SETTINGS
  // ---------------------------------------------------------------------------

  // If true, also reports custom properties that are defined (in destFile or
  // an extraCustomPropsFiles entry) but never referenced via var() in any
  // scanned CSS file. Opt-in because it re-runs the Style Dictionary
  // transform pipeline over the token sources to resolve, when possible, the
  // .mjs source file for each unused property. Default: false.
  checkUnused: true,

  // When checkUnused is true: if true (default), custom properties sourced
  // from a token file under node_modules (e.g. a third-party token package)
  // are never reported as unused — the consuming project isn't expected to
  // prune those.
  ignoreUnusedInNodeModules: true,

  // Directory containing the CSS files to scan for unresolved custom properties
  dirToCheck: '../src',

  // Regular expressions for custom property names to exclude from the check.
  // Useful for intentionally private/internal props (e.g. prefixed with --_).
  excludePattern: [
    /^--_/,
  ]
};

export default config;


