/// <reference types="node" />
// build-tokens-src/config.mjs
// Reads the --config flag from argv, imports the project config file,
// resolves all paths and exports them for build-tokens.mjs.
//
// Keeping this logic separate from the entry point makes it easier to test
// and reuse in other scripts.

/* globals process */

import * as path from 'node:path';
import { pathToFileURL } from 'node:url';
import { splitSourceEntries } from './source-prefixes.mjs';

// ---------------------------------------------------------------------------
// Read the --config flag
// ---------------------------------------------------------------------------
const args = process.argv.slice(2);
const configFlagIndex = args.indexOf('--config');

if (configFlagIndex === -1 || !args[configFlagIndex + 1]) {
  // eslint-disable-next-line no-console
  console.error(
    'Error: you must specify the config file with --config ./path/to/config/file'
  );
  process.exit(1);
}

const configArgPath = args[configFlagIndex + 1];
export const configAbsPath = path.resolve(process.cwd(), configArgPath);
export const configDir     = path.dirname(configAbsPath);

// ---------------------------------------------------------------------------
// Import the project config
// ---------------------------------------------------------------------------
const buildConfig = (await import(pathToFileURL(configAbsPath).href)).default;

// Helper: resolves a path relative to the config directory.
// Leaves already-absolute paths untouched.
/** @param {string} p */
const resolveFromConfig = (p) => path.resolve(configDir, p);

// ---------------------------------------------------------------------------
// Path resolution
// ---------------------------------------------------------------------------

// CSS output
export const buildPath = resolveFromConfig(buildConfig.buildPath);
export const destFile  = buildConfig.destFile;

// Stylelint
export const stylelintConfigPath = resolveFromConfig(buildConfig.stylelintConfigPath);

// JSON — platform is active only if jsonBuildPath is set in the config
const jsonBuildPathRaw = buildConfig.jsonBuildPath ?? null;
export const jsonBuildPath = jsonBuildPathRaw ? resolveFromConfig(jsonBuildPathRaw) : null;

// jsonDestFile: base name (no extension) for the aggregated output file.
// null  → one file per source (mirrors the source structure)
// string → single aggregated file (e.g. 'tokens' → 'tokens.jsonc')
// The extension is added automatically based on jsonFormat.
export const jsonDestFile = buildConfig.jsonDestFile ?? null;

// jsonFormat: controls output format for the generated JSON token files.
// 'jsonc' → .jsonc extension + generated-file disclaimer header
// 'json'  → plain .json, no disclaimer
// Any value other than 'jsonc' is normalised to 'json'.
export const jsonFormat = buildConfig.jsonFormat === 'jsonc' ? 'jsonc' : 'json';

// jsonExpression: controls how math expressions in dimension token values are handled.
//   'keep'    (default) — write the expression as-is
//   'calc'    — wrap in CSS calc()
//   'resolve' — evaluate numerically; unit inherited from the first referenced token
const VALID_EXPR_MODES = ['keep', 'calc', 'resolve'];
export const jsonExpression = VALID_EXPR_MODES.includes(buildConfig.jsonExpression)
  ? buildConfig.jsonExpression
  : 'resolve';

// pxToRem: if true (default), dimension token values expressed in px are
// converted to rem in the generated CSS (see the size/pxToRem-smart
// transform in build-tokens-src/transforms.mjs). Values in other units
// (em, %, vh, dvw, ...) are never touched regardless of this option.
export const pxToRem = buildConfig.pxToRem !== false;

// mergeCustomProps: if true, custom properties already present in the CSS
// destination file take priority over the ones generated by this build (see
// build-tokens-src/merge-css.mjs). It can also be an array of strings/RegExps:
// only the properties generated by the token source files matching one of its
// entries are merged. An empty or invalid value means false. Default: false.
/** @type {boolean|(string|RegExp)[]} */
export const mergeCustomProps = (() => {
  const value = buildConfig.mergeCustomProps;
  if (value === true) return true;
  if (Array.isArray(value)) {
    const entries = value.filter((entry) => typeof entry === 'string' || entry instanceof RegExp);
    return entries.length ? entries : false;
  }
  return false;
})();

// addLayer: wraps the generated custom properties inside a CSS `@layer`
// at-rule (see formats/css.mjs), e.g. `@layer project { :root { ... } }`.
// Set to null, undefined or false (default) to emit no layer.
export const addLayer = buildConfig.addLayer ? String(buildConfig.addLayer).trim() : null;

// customPropsGroups: custom properties whose first hyphen-separated name
// segment matches one of a group's prefixes are pulled out, labelled with
// that group's name and moved to the beginning of the generated CSS file, in
// group-list order (see formats/css.mjs). Each entry: { name, prefixes }.
// Default: [].
export const customPropsGroups = Array.isArray(buildConfig.customPropsGroups)
  ? buildConfig.customPropsGroups
  : [];

// ---------------------------------------------------------------------------
// Source: resolve patterns relative to the config directory and normalise to
// forward-slash absolute paths (fast-glob, used internally by Style Dictionary,
// requires forward slashes even on Windows). See resolve-source-paths.mjs.
//
// WARNING: in the project config file, avoid building glob patterns with
// path.join() — it may corrupt the pattern syntax. Use template literals:
//   OK:  `${minimo_path}/**/*.{json,mjs}`
//   NO:  path.join(minimo_path, '/**/*.{json,mjs}')
//
// sourceModes: alternative to `source`, for a light/dark (or other) custom
// properties split — see build-tokens-src/build-source-modes.mjs. When set
// (buildConfig.sourceModes is a non-null object), `source` is ignored and
// each mode's own array of source patterns is resolved the same way.
//
// Entries of `source` / of each mode can also be `{ src, prefix }` objects,
// to render the custom properties of those files with a prefix (see
// source-prefixes.mjs). They are flattened here into plain patterns for
// Style Dictionary; the prefixed ones are also collected in
// `prefixedSources`, to be registered by build-tokens.mjs.
// ---------------------------------------------------------------------------
const sourceModesRaw = buildConfig.sourceModes ?? null;

/** @type {import('./source-prefixes.mjs').PrefixedSource[]} */
export const prefixedSources = [];

/**
 * @param {Parameters<typeof splitSourceEntries>[0]} entries
 * @returns {string[]}
 */
const parseSourceEntries = (entries) => {
  const { patterns, prefixed } = splitSourceEntries(entries, configDir);
  prefixedSources.push(...prefixed);
  return patterns;
};

export const sourceModes = sourceModesRaw
  ? Object.fromEntries(
    Object.entries(sourceModesRaw).map(([mode, modeSource]) => [
      mode,
      parseSourceEntries(modeSource),
    ])
  )
  : null;

// sourceModesBase: the mode whose declarations are written to the top-level
// `:root { ... }` block (the others are nested under
// `@media (prefers-color-scheme: <mode>) { ... }`). Default: the first key
// of sourceModes (insertion order), e.g. 'light'. Ignored when sourceModes
// is not set.
export const sourceModesBase = sourceModes
  ? (Object.prototype.hasOwnProperty.call(sourceModes, buildConfig.sourceModesBase)
    ? buildConfig.sourceModesBase
    : Object.keys(sourceModes)[0])
  : null;

if (sourceModes && buildConfig.sourceModesBase && sourceModesBase !== buildConfig.sourceModesBase) {
  // eslint-disable-next-line no-console
  console.warn(
    `[build-tokens] config: sourceModesBase "${buildConfig.sourceModesBase}" is not a key of sourceModes — falling back to "${sourceModesBase}"`
  );
}

export const source = sourceModes ? null : parseSourceEntries(buildConfig.source);
