// build-tokens-src/merge-css.mjs
// Supports the `mergeCustomProps` config option: pre-existing custom
// properties in the CSS destination file take priority over the ones
// generated by the current build (manual overrides/additions survive rebuilds).
//
// Usage (single `source` build):
//   1. Call loadExistingCustomProps(absDestPath) BEFORE Style Dictionary runs,
//      since it reads the file that is about to be overwritten.
//   2. The css/variables-sorted format (see formats/css.mjs) calls
//      mergeCustomProps(generatedMap) while building the output, right before
//      serialising the final CSS text.
//
// `mergeCustomProps` may also be an array of strings/RegExps: in that case
// only the generated properties whose token source file matches one of the
// entries are merged (pre-existing value wins); the others are overwritten by
// the generated value. Pre-existing properties that are no longer generated
// (no token, hence no source file) are always kept. See matchesSource().
//
// Usage (sourceModes build, see build-source-modes.mjs):
//   1. Call loadExistingCustomPropsScoped(absDestPath, baseMode) BEFORE any
//      of the per-mode Style Dictionary instances run.
//   2. The css/variables-sorted format calls mergeCustomProps(generatedMap, mode)
//      once per mode. Declarations are matched only within the same mode's
//      scope (the base `:root { ... }` block, or the `:root { ... }` nested
//      inside that mode's `@media (prefers-color-scheme: <mode>) { ... }`),
//      so the same custom property name defined with different values across
//      modes is never mixed up.

import { existsSync, readFileSync } from 'node:fs';

const CUSTOM_PROP_RE = /^\s*--([\w-]+):\s*(.+)$/gm;

/**
 * Parses `--name: <tail>` declarations out of a CSS text block. <tail> is
 * captured verbatim (value, terminating `;`, and anything else on the same
 * line, e.g. a trailing comment) so it round-trips unchanged through a merge.
 * Only single-line declarations are supported.
 * @param {string} cssText
 * @returns {Record<string,string>} name → declaration-tail map, in first-seen order
 */
export const parseCustomProps = (cssText) => {
  /** @type {Record<string,string>} */
  const map = {};
  for (const match of cssText.matchAll(CUSTOM_PROP_RE)) {
    let tail = match[2].trim();
    // A multi-line comment is cut at the end of the line (only single-line
    // declarations are parsed): close it, or the resulting CSS would be invalid
    if (tail.lastIndexOf('/*') > tail.lastIndexOf('*/')) tail += ' */';
    map[match[1]] = tail;
  }
  return map;
};

// Returns the index of the closing brace matching the `{` at openIndex, by
// simple depth counting. Braces inside comments/strings are not special-cased
// — not expected to occur in generated custom-properties CSS.
/** @param {string} text @param {number} openIndex */
const matchBraces = (text, openIndex) => {
  let depth = 0;
  for (let i = openIndex; i < text.length; i++) {
    if (text[i] === '{') depth++;
    else if (text[i] === '}') {
      depth--;
      if (depth === 0) return i;
    }
  }
  return -1;
};

// Finds every @media (prefers-color-scheme: <mode>) { ... } block in a
// previously generated sourceModes CSS destFile, with absolute character
// offsets into cssText. Used to split the file into per-mode scopes (see
// splitModeScopes() below) and, by check-unresolved-custom-props.mjs, to
// tell which mode a given custom property declaration belongs to.
// An optional wrapping `@layer { ... }` (addLayer option) is transparent to
// this search, since it only looks for the `@media (prefers-color-scheme: ...)`
// pattern itself.
// @param {string} cssText
// @returns {{mode:string,start:number,end:number}[]} start/end are the
//   indices of the block's outer `{`/matching `}` (inclusive)
export const findMediaModeBlocks = (cssText) => {
  const MEDIA_RE = /@media\s*\(\s*prefers-color-scheme\s*:\s*([\w-]+)\s*\)\s*\{/g;
  /** @type {{mode:string,start:number,end:number}[]} */
  const mediaBlocks = [];
  for (const match of cssText.matchAll(MEDIA_RE)) {
    const openIdx = match.index + match[0].length - 1;
    const closeIdx = matchBraces(cssText, openIdx);
    if (closeIdx === -1) continue;
    mediaBlocks.push({ mode: match[1], start: openIdx, end: closeIdx });
  }
  return mediaBlocks;
};

// Splits a previously generated sourceModes CSS destFile into per-mode
// scopes (see build-source-modes.mjs for the shape of the generated file):
//   - the base scope is the top-level `:root { ... }` block, i.e. the one
//     NOT nested inside a `@media (prefers-color-scheme: ...)` rule
//   - every other scope is the `:root { ... }` block nested inside its own
//     `@media (prefers-color-scheme: <mode>) { ... }` rule
// @param {string} cssText
// @returns {Record<string,string>} mode → CSS body text (base mode keyed as '__base__')
const splitModeScopes = (cssText) => {
  /** @type {Record<string,string>} */
  const scopes = {};

  // 1. Every @media (prefers-color-scheme: <mode>) { ... } block, and the
  // :root { ... } body nested inside each one.
  const mediaBlocks = findMediaModeBlocks(cssText);
  for (const { mode, start, end } of mediaBlocks) {
    const body = cssText.slice(start + 1, end);
    const rootMatch = /:root\s*\{/.exec(body);
    if (rootMatch) {
      const rootOpen = rootMatch.index + rootMatch[0].length - 1;
      const rootClose = matchBraces(body, rootOpen);
      if (rootClose !== -1) {
        scopes[mode] = body.slice(rootOpen + 1, rootClose);
      }
    }
  }

  // 2. The base :root { ... } block: the first one not nested inside any of
  // the media blocks found above.
  const ROOT_RE = /:root\s*\{/g;
  for (const match of cssText.matchAll(ROOT_RE)) {
    const openIdx = match.index + match[0].length - 1;
    const insideMedia = mediaBlocks.some((b) => openIdx > b.start && openIdx < b.end);
    if (insideMedia) continue;
    const closeIdx = matchBraces(cssText, openIdx);
    if (closeIdx === -1) continue;
    scopes.__base__ = cssText.slice(openIdx + 1, closeIdx);
    break;
  }

  return scopes;
};

// `true` = merge every source; an array = merge only the properties generated
// by the token source files matching one of its entries. Set by the
// loadExistingCustomProps*() functions.
/** @type {true|(string|RegExp)[]} */
let mergeSources = true;

/**
 * Whether a token source file matches one of the `mergeCustomProps` array
 * entries: a string matches if it is contained in the file path (path
 * separators normalised to `/`), a RegExp if it tests true against it.
 * @param {(string|RegExp)[]} sources
 * @param {string|undefined} filePath token source file path
 * @returns {boolean}
 */
const matchesSource = (sources, filePath) => {
  if (!filePath) return false;
  const normalized = filePath.replace(/\\/g, '/');
  return sources.some((entry) => {
    if (entry instanceof RegExp) {
      entry.lastIndex = 0;
      return entry.test(normalized);
    }
    return normalized.includes(entry.replace(/\\/g, '/'));
  });
};

// null = merge disabled, or destination file not found yet (first build)
/** @type {Record<string,string>|null} */
let existingCustomProps = null;

// Per-mode equivalent of existingCustomProps, populated by
// loadExistingCustomPropsScoped() for a sourceModes build.
/** @type {Record<string, Record<string,string>>|null} */
let scopedExistingCustomProps = null;

/**
 * Reads the CSS destination file (if it exists) and stores a name → value
 * map of its current custom properties for later merging.
 * @param {string} absDestPath absolute path of the CSS file to read
 * @param {true|(string|RegExp)[]} [sources] `true` merges every source, an
 *   array only the token source files matching one of its entries (default: true)
 * @returns {Record<string,string>|null}
 */
export const loadExistingCustomProps = (absDestPath, sources = true) => {
  mergeSources = sources;
  existingCustomProps = existsSync(absDestPath)
    ? parseCustomProps(readFileSync(absDestPath, 'utf8'))
    : null;
  return existingCustomProps;
};

/**
 * sourceModes equivalent of loadExistingCustomProps(): reads the CSS
 * destination file (if it exists) and stores a per-mode name → value map,
 * scoped to each mode's own `:root { ... }` block (see splitModeScopes()).
 * @param {string} absDestPath absolute path of the CSS file to read
 * @param {string} baseMode mode whose declarations live in the top-level,
 *   non-nested `:root { ... }` block (no default — always passed explicitly
 *   by build-source-modes.mjs, from the resolved sourceModesBase)
 * @param {true|(string|RegExp)[]} [sources] `true` merges every source, an
 *   array only the token source files matching one of its entries (default: true)
 * @returns {Record<string, Record<string,string>>|null}
 */
export const loadExistingCustomPropsScoped = (absDestPath, baseMode, sources = true) => {
  mergeSources = sources;
  if (!existsSync(absDestPath)) {
    scopedExistingCustomProps = null;
    return scopedExistingCustomProps;
  }
  const scopes = splitModeScopes(readFileSync(absDestPath, 'utf8'));
  scopedExistingCustomProps = {};
  if (scopes.__base__ !== undefined) {
    scopedExistingCustomProps[baseMode] = parseCustomProps(scopes.__base__);
  }
  for (const [mode, body] of Object.entries(scopes)) {
    if (mode === '__base__') continue;
    scopedExistingCustomProps[mode] = parseCustomProps(body);
  }
  return scopedExistingCustomProps;
};

/**
 * Merges freshly generated custom properties with the ones previously loaded
 * via loadExistingCustomProps() / loadExistingCustomPropsScoped(). Pre-existing
 * values take priority; custom properties found only in the pre-existing file
 * (no longer generated) are kept as well. When the merge is limited to some
 * token source files (array option), a generated property whose source file
 * does not match is not overridden by its pre-existing value.
 * @param {Record<string,string>} generated name → value map produced by this build
 * @param {string|null} [mode] when set (sourceModes build), looks up the
 *   pre-existing props scoped to this mode instead of the flat/global map (default: null)
 * @param {Record<string,string>} [sourceFileMap] property name → token source
 *   file path, used only when the merge is limited to some sources (default: {})
 * @returns {Record<string,string>}
 */
export const mergeCustomProps = (generated, mode = null, sourceFileMap = {}) => {
  const existing = mode !== null ? scopedExistingCustomProps?.[mode] : existingCustomProps;
  if (!existing) return generated;
  if (mergeSources === true) return { ...generated, ...existing };

  const merged = { ...generated };
  for (const [name, tail] of Object.entries(existing)) {
    if (!(name in generated) || matchesSource(mergeSources, sourceFileMap[name])) {
      merged[name] = tail;
    }
  }
  return merged;
};
